site_name: "iharm2d v4: wiki"
repo_url: https://github.com/AFD-Illinois/iharm2d_v4
repo_name: iharm2d_v4

nav:
  - Home: index.md
  - Getting Started:
    - getting-started/quickstart.md
    - getting-started/compile-time-parameters.md
    - getting-started/runtime-parameters.md
    - getting-started/output-data-format.md
  - GRMHD Theory: theory.md
  - Control flow and FluidState mapping: iharm-control-flow.md
  - Tests:
    - tests/advection.md
    - tests/entropy_wave.md

markdown_extensions:
  - pymdownx.arithmatex:        # LaTeX math support ($E = mc^2$)
      generic: true

  - pymdownx.highlight:           # Syntax highlighting for code blocks
      use_pygments: true          # Uses Pygments library for coloring
      pygments_lang_class: true   # Adds language class to HTML (for CSS targeting)

  - pymdownx.tabbed:            # Lets you create tabs in docs
      alternate_style: true

  - pymdownx.details            # Collapsible sections (click to expand)

  - pymdownx.superfences:       # Enhanced code blocks
      custom_fences:
        - name: mermaid   # Lets them embed Mermaid diagrams
          class: mermaid  # (flowcharts, sequence diagrams) in code blocks
          format: !!python/name:pymdownx.superfences.fence_code_format

  - md_in_html
  - tables

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.tracking     # URL updates as you scroll through sections
    - navigation.indexes      # Section pages (index.md inside folders become section landing pages)
    - navigation.expand       # Sidebar sections start expanded
    - content.code.annotate   # Add numbered annotations to code blocks

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - tags              # Tag pages and filter by tags
  - search            # Built-in search bar (basically always want this)